# In-Class Programming Activity, Day 12

```{r}
library(mosaicData)
library(ggplot2)
library(ISLR)
```

# Generating simulated data

```{r}
n_cases <- 10000
red_mean <- c(1, 0)
green_mean <- c(0, -1)
blue_mean <- c(-1, 1)
covar_red <- matrix(c(3,-1.7, -1.7, 2), nrow = 2, ncol = 2)
covar_blue <- matrix(c(2, 1.5, 1.5, 3), nrow = 2, ncol = 2)
One <- matrix(rnorm(2*n_cases), ncol = 2, nrow=n_cases)
Two <- matrix(rnorm(2*n_cases), ncol = 2)
Three <- matrix(rnorm(2*n_cases), ncol = 2, nrow = n_cases)

```

```{r}
Red <- One %*% chol(covar_red) + outer(rep(1, n_cases), red_mean)
Green <- Two %*% chol(covar_red) + outer(rep(1, n_cases), green_mean)
Blue <- Three %*% chol(covar_blue) + outer(rep(1, n_cases), blue_mean)
```

```{r}
Red <- data.frame(x = Red[,1], y = Red[,2], class = "red", stringsAsFactors = FALSE)
Green <- data.frame(x = Green[,1], y = Green[,2], class = "green", stringsAsFactors = FALSE)
Blue <- data.frame(x = Blue[,1], y = Blue[,2], class = "blue", stringsAsFactors = FALSE)
```


```{r}
Same_sigma <- rbind(Red, Green)
Different_sigma <- rbind(Red, Blue)
```

```{r}
plot(y ~ x, data = Same_sigma, col = alpha(Same_sigma$class, .02), pch = 20)
```

```{r}
plot(y ~ x, data = Different_sigma, col = alpha(Different_sigma$class, .02), pch = 20)
```

# LDA and QDA

```{r}
library(MASS)
```

```{r}
mod_LDA_one <- lda(class ~ x+ y, data = Same_sigma)
test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)
```

# Confusion matrices

```{r}
table(Same_sigma$class, test_LDA_one$class)
```

```{r}
mod_QDA_one <- MASS::qda(class ~ x + y, data = Same_sigma)
test_QDA_one <- predict(mod_QDA_one, newdata = Same_sigma)
table(Same_sigma$class, test_QDA_one$class)
```

```{r}
mod_LDA_two <- MASS::lda(class ~ x + y, data = Different_sigma)
mod_QDA_two <- MASS::qda(class ~ x + y, data = Different_sigma)
test_LDA_two <- predict(mod_LDA_two, newdata = Different_sigma)
test_QDA_two <- predict(mod_QDA_two, newdata = Different_sigma)
table(Different_sigma$class, test_LDA_two$class)
table(Different_sigma$class, test_QDA_two$class)
```


## Test statements

```{r}
scoreActivity::score253(12)
```