# In-Class Programming Activity, Day 15

```{r}
library(mosaicData)
library(ggplot2)
library(ISLR)
library(pls)
library(glmnet)
```

```{r}
#download.file("http://tiny.cc/dcf/mona.rda", destfile = "mona.rda")
```
# Overview

```{r}
load("mona.rda")
```

```{r}
X <- t(mona) - mean(mona[])
```

```{r}
X_rand <- matrix(rnorm(191*250), ncol = 191)
X_corr <- X_rand %*% chol(var(X))

image(X[sample(1:250, size = 250), sample(1:191, size = 191)], asp = 1, xaxt = 'n', yaxt = 'n', bty = "n" )
```
# Sparse beta

```{r}
beta <- c(rep(0, 175), rep(2,4), rep(5, 4), rep(-3, 4), rep(-4,4))
beta <- sample(beta)
```

# The output

```{r}
Y_pure <- X %*% beta
Y_real <- X %*% beta + rnorm(nrow(X), 0.1 * sd(X[]))
```

# Least Squares

```{r}
mod_lm <- lm(Y_pure ~ X)
beta_hat_pure <- coef(mod_lm)
plot(beta, beta_hat_pure[-1])
```

```{r}
mod_lm_real <- lm(Y_real ~ X)
beta_hat_real <- coef(mod_lm)
plot(beta, beta_hat_real[-1])
```

# The lasso estimator
```{r}
lasso_mod <- cv.glmnet(X, Y_real, alpha = 1)
beta_lasso <- predict(lasso_mod, type = "coefficients", s = lasso_mod$lambda.min)
plot(jitter(beta), beta_lasso[-1])
```

# Principal components

```{r}
sing_vals <- svd(X)$d
sing_vals_rand <- svd(X_rand)$d
sing_vals_corr <- svd(X_corr)$d
Rsq <- cumsum(sing_vals^2) / sum(sing_vals^2)
Rsq_rand <- cumsum(sing_vals_rand^2) / sum(sing_vals_rand^2)
Rsq_corr <- cumsum(sing_vals_corr^2) / sum(sing_vals_corr^2)
n99 <- 1 + sum(Rsq < 0.99)
n99_rand <- 1 + sum(Rsq_rand < 0.99)
n99_corr <- 1 + sum(Rsq_corr < 0.99)

```

```{r}
pcr.fit <- pcr(Y_real ~ X, scale = TRUE, validation = "CV")
```


## Test statements

```{r}
scoreActivity::score253(15)
```