# In-Class Programming Activity, Day 17

```{r}
library(mosaicData)
library(ggplot2)
library(tree)
library(ISLR)
library(pls)
library(glmnet)
```

```{r}
Cartoon_data <- data.frame(
  x = 1:8, y = c(2,5,1,3,8,5,4,6), class = c("A", "B", "A", "A", "B", "B", "A", "B")
)
```


#perfectly pure trees
```{r}
pure <- tree.control(8, mincut = 0, minsize = 1, mindev = 0)
```

# regression tree
```{r}
rtree_pure <- tree(y~x, data = Cartoon_data, control = pure)
plot(rtree_pure)
text(rtree_pure)
```

# classification tree
```{r}
ctree_pure <- tree(class~x, data = Cartoon_data, control = pure)
plot(ctree_pure)
text(ctree_pure)
```

# evaluating the tree
```{r}
predict(rtree_pure)
predict(ctree_pure)
predict(rtree_pure, newdata = data.frame(x = 3))
predict(ctree_pure, newdata = data.frame(x=7))

```

# pruning the tree

```{r}
rtree_5 <- prune.tree(rtree_pure, best = 5)
ctree_2 <- prune.misclass(ctree_pure, best = 2)
```

# building a real classifier
```{r}
pure_for_cps <- tree.control(nrow(CPS85), mincut = 0, minsize = 1, mindev = 0)
Sector_classifier <- tree(sector ~ wage + sex + educ + exper, data = mosaicData::CPS85, control = pure_for_cps)

final_tree <- prune.misclass(Sector_classifier, best = 20)
```

```{r}
plot(final_tree)
#text(final_tree)
```


## Test statements

```{r}
#scoreActivity::score253(17)
```